/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[lang]': RouteRecordInfo<'/[lang]', '/:lang(fr|en)', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Home': RouteRecordInfo<'Home', '/:lang(fr|en)', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'NotFound': RouteRecordInfo<'NotFound', '/:lang(fr|en)/:path(.*)*', { lang: ParamValue<true>, path?: ParamValueZeroOrMore<true> }, { lang: ParamValue<false>, path?: ParamValueZeroOrMore<false> }>,
    'Components': RouteRecordInfo<'Components', '/:lang(fr|en)/components', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Dialogs': RouteRecordInfo<'Dialogs', '/:lang(fr|en)/dialogs', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Forbidden': RouteRecordInfo<'Forbidden', '/:lang(fr|en)/forbidden', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Loading': RouteRecordInfo<'Loading', '/:lang(fr|en)/loading', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Notifications': RouteRecordInfo<'Notifications', '/:lang(fr|en)/notifications', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Settings': RouteRecordInfo<'Settings', '/:lang(fr|en)/settings', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Validations': RouteRecordInfo<'Validations', '/:lang(fr|en)/validations', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Version': RouteRecordInfo<'Version', '/:lang(fr|en)/version', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
  }
}
