/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[lang]': RouteRecordInfo<'/[lang]', '/:lang(fr|en)', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Home': RouteRecordInfo<'Home', '/:lang(fr|en)', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'NotFound': RouteRecordInfo<'NotFound', '/:lang(fr|en)/:path(.*)*', { lang: ParamValue<true>, path?: ParamValueZeroOrMore<true> }, { lang: ParamValue<false>, path?: ParamValueZeroOrMore<false> }>,
    'HomeWithAuth': RouteRecordInfo<'HomeWithAuth', '/:lang(fr|en)/auth', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'DeleteAccount': RouteRecordInfo<'DeleteAccount', '/:lang(fr|en)/delete-account', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'EditPassword': RouteRecordInfo<'EditPassword', '/:lang(fr|en)/edit-password', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'EditProfile': RouteRecordInfo<'EditProfile', '/:lang(fr|en)/edit-profile', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Forbidden': RouteRecordInfo<'Forbidden', '/:lang(fr|en)/forbidden', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/:lang(fr|en)/forgot-password', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Login': RouteRecordInfo<'Login', '/:lang(fr|en)/login', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Profile': RouteRecordInfo<'Profile', '/:lang(fr|en)/profile', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Register': RouteRecordInfo<'Register', '/:lang(fr|en)/register', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/:lang(fr|en)/reset-password', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'SetPassword': RouteRecordInfo<'SetPassword', '/:lang(fr|en)/set-password', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'Settings': RouteRecordInfo<'Settings', '/:lang(fr|en)/settings', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    'ConfirmEmail': RouteRecordInfo<'ConfirmEmail', '/:lang(fr|en)/verify', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
  }
}
