name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
    paths:
    - packages/**
  pull_request:
    branches:
    - main
    paths:
    - packages/**

env:
  PROJECT_UI_BUILD: 'build --workspaces --if-present'
  PROJECT_UI_LINT: 'lint --workspaces --if-present'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        uses: amilochau/github-actions/build/node@v4
        with:
          npmBuildCommand: ${{ env.PROJECT_UI_BUILD }}
          npmLintCommand: ${{ env.PROJECT_UI_LINT }}
