name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
    paths:
    - packages/**
  pull_request:
    branches:
    - main
    paths:
    - packages/**

env:
  PROJECT_UI_OUTPUT: '/packages/core-vue3'
  PROJECT_UI_BUILD: 'build --workspaces --if-present'
  PROJECT_UI_LINT: 'lint --workspaces --if-present'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        uses: amilochau/github-actions/build/node@v3
        with:
          relativeOutputPath: ${{ env.PROJECT_UI_OUTPUT }}
          npmBuildScript: ${{ env.PROJECT_UI_BUILD }}
          npmLintScript: ${{ env.PROJECT_UI_LINT }}
