name: Build

on:
  push:
    branches:
    - main
    paths:
    - packages/**
  pull_request:
    branches:
    - main
    paths:
    - packages/**

env:
  PROJECT_UI_WORKSPACE: './packages/core-vue3'
  PROJECT_UI_OUTPUT: ''

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        uses: amilochau/github-actions/build/node@v3
        with:
          projectWorkspace: ${{ env.PROJECT_UI_WORKSPACE }}
          relativeOutputPath: ${{ env.PROJECT_UI_OUTPUT }}
