name: Deploy libraries
run-name: Deploy libraries - ${{ github.ref }}

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECT_UI_BUILD: 'build --workspaces --if-present'
  PROJECT_UI_PUBLISH: 'publish --workspace=packages/core-vue3 --workspace=packages/core-vue3-auth --provenance --access public'

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Copy readme file
        shell: pwsh
        run: |
          Copy-Item "./README.md" -Destination "./packages/core-vue3"
          Copy-Item "./README.md" -Destination "./packages/core-vue3-auth"
      - name: Deploy library
        uses: amilochau/github-actions/release/npm@v4
        with:
          npmBuildCommand: ${{ env.PROJECT_UI_BUILD }}
          npmPublishCommand: ${{ env.PROJECT_UI_PUBLISH }}
          npmjsComToken: ${{ secrets.NPMJSCOM_TOKEN }}
