name: Deploy libraries
run-name: Deploy libraries - ${{ github.ref }}

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECT_UI_PUBLISH: 'publish --workspace=packages/core-vue3 --workspace=packages/core-vue3-auth'

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    steps:
      - uses: actions/checkout@v3
      - name: Copy readme file
        shell: pwsh
        run: |
          Copy-Item "./README.md" -Destination "./packages/core-vue3"
          Copy-Item "./README.md" -Destination "./packages/core-vue3-auth"
      - name: Deploy library
        uses: amilochau/github-actions/release/npm@v3
        with:
          npmPublishCommand: ${{ env.PROJECT_UI_PUBLISH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmjsComToken: ${{ secrets.NPMJSCOM_TOKEN }}
