name: Deploy libraries

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECT_UI_WORKSPACE: './packages/core-vue3'

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    steps:
      - uses: actions/checkout@v3
      - name: Deploy libraries
        uses: amilochau/github-actions/release/npm@v3
        with:
          projectWorkspace: ${{ env.PROJECT_UI_WORKSPACE }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmjsComToken: ${{ secrets.NPMJSCOM_TOKEN }}
