name: Deploy libraries

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECT_UI_PUBLISH: 'publish --workspace=packages/core-vue3'

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    steps:
      - uses: actions/checkout@v3
      - name: Deploy libraries
        uses: amilochau/github-actions/release/npm@main
        with:
          npmPublishCommand: ${{ env.PROJECT_UI_PUBLISH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmjsComToken: ${{ secrets.NPMJSCOM_TOKEN }}
